name: Nightly
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      version:
        description: Nightly version number (e.g. 20221125)
        required: true
        type: string
      language:
        description: Configured artefacts for the language will be built and pushed
        required: true
        type: choice
        default: "ruby"
        options:
          - java
          - ruby

jobs:
  ruby:
    if: inputs.language == 'ruby'
    name: Ruby
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        gem:
          - selenium-devtools
          - selenium-webdriver
    with:
      name: Release
      cache-key: rb-nightly-${{ matrix.gem }}
      run: |
        export GEM_HOST_API_KEY="Bearer $GITHUB_TOKEN"
        bazel run //rb:${{ matrix.gem }}-bump-nightly-version ${{ inputs.version }}
        bazel run //rb:${{ matrix.gem }}-release-nightly

  java:
    if: inputs.language == 'java'
    name: Java
    uses: ./.github/workflows/bazel.yml
    with:
      name: Release
      cache-key: java-nightly
      run: ./go publish-maven-snapshot

  grid:
    runs-on: ubuntu-latest
    if: inputs.language == 'java'
    steps:
      - name: Java Build
        uses: ./.github/workflows/bazel.yml
        with:
          name: Build Release
          cache-key: java-nightly
          run: ./go publish-maven-snapshot
      - name: Release Nightly Grid
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          title: "Nightly"
          prerelease: true
          files: build/dist/*.jar
